name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
      options: --cpus 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build